# Generated by Django 4.0 on 2022-01-18 21:32

import address.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import inscription.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, verbose_name='Commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='BaseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], default='M.', max_length=3, verbose_name='Civilité')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Ville de naissance')),
                ('birth_country', django_countries.fields.CountryField(max_length=255, verbose_name='Pays de naissance')),
                ('mail', models.EmailField(max_length=255, verbose_name='Mail')),
                ('street_type', models.CharField(choices=[('Boulevard', 'Boulevard'), ('Avenue', 'Avenue'), ('Cours', 'Cours'), ('Place', 'Place'), ('Rue', 'Rue'), ('Route', 'Route'), ('Voie', 'Voie'), ('Chemin', 'Chemin'), ('Square', 'Square'), ('Impasse', 'Impasse'), ('Rond-point', 'Rond-point'), ('Quai', 'Quai')], default='Rue', max_length=30, verbose_name='Type de rue')),
                ('street_number', models.CharField(max_length=30, verbose_name='Numéro de rue')),
                ('street', models.CharField(max_length=30, verbose_name='Rue')),
                ('comp_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément 1')),
                ('comp_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément 2')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Code postal')),
                ('country', django_countries.fields.CountryField(max_length=255, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('hash', models.CharField(default=inscription.utils.create_hash, max_length=30, unique=True)),
                ('photo', models.ImageField(null=True, upload_to=inscription.utils.nom_photo)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Adresse')),
                ('commune_naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.commune', verbose_name='Commune de naissance')),
                ('departement_naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département de naissance')),
            ],
        ),
    ]
