# Generated by Django 4.0 on 2022-01-22 16:09

import address.models
from django.db import migrations, models
import django.db.models.deletion
import inscription.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='Sociopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Code Sociopro')),
                ('name', models.CharField(max_length=100, verbose_name='Catégorie sociopro')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code INSEE')),
                ('name', models.CharField(max_length=50, verbose_name='Commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='BaseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('civility', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], default='M.', max_length=3, verbose_name='Civilité')),
                ('genre', models.CharField(choices=[('Il', 'Il'), ('Elle', 'Elle'), ('Iel', 'Iel')], default='Iel', help_text="Veux-tu que l'on parle de toi en disant il, elle ou iel ?", max_length=5, verbose_name='Pronom')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('nom_usage', models.CharField(max_length=255, verbose_name="Nom d'usage")),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('hash', models.CharField(default=inscription.utils.create_hash, max_length=30, unique=True)),
                ('photo', models.ImageField(null=True, upload_to=inscription.utils.nom_photo)),
                ('resp2', models.BooleanField(verbose_name='Deuxième responsable')),
                ('nom_resp1', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('nom_resp2', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('prenom_resp1', models.CharField(max_length=255, verbose_name='Prénom')),
                ('prenom_resp2', models.CharField(max_length=255, verbose_name='Prénom')),
                ('type_resp1', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('autre', 'Autre responsable légal ou référent')], default='mere', max_length=5, verbose_name='Lien de parenté')),
                ('type_resp2', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('autre', 'Autre responsable légal ou référent')], default='mere', max_length=5, verbose_name='Lien de parenté')),
                ('email_resp1', models.EmailField(max_length=255, verbose_name='Email')),
                ('email_resp2', models.EmailField(max_length=255, verbose_name='Email')),
                ('tel_resp1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone')),
                ('tel_resp2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='address.address', verbose_name='Adresse')),
                ('adresse_resp1', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='rep1', to='address.address', verbose_name='Adresse')),
                ('adresse_resp2', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='rep2', to='address.address', verbose_name='Adresse')),
                ('commune_naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.commune', verbose_name='Commune de naissance')),
                ('departement_naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département de naissance')),
                ('pays_naissance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.pays', verbose_name='Pays de naissance')),
                ('sociopro_resp1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep1', to='inscription.sociopro', verbose_name='Profession')),
                ('sociopro_resp2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp2', to='inscription.sociopro', verbose_name='Profession')),
            ],
        ),
    ]
