# Generated by Django 4.0 on 2022-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='code',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departement',
            name='nom',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
