# Generated by Django 4.0 on 2022-01-24 20:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_baseeleve_nationalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeleve',
            name='dys',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DL', 'Dyslexie'), ('DC', 'Dyscalculie'), ('DP', 'Dyspraxie'), ('DG', 'Dysgraphie'), ('DO', 'Dysorthographie')], max_length=14, null=True, verbose_name='Troubles cognitifs'),
        ),
        migrations.AddField(
            model_name='baseeleve',
            name='ville_natale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville natale'),
        ),
        migrations.AlterField(
            model_name='baseeleve',
            name='commune_naissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.commune', verbose_name='Commune de naissance'),
        ),
        migrations.AlterField(
            model_name='baseeleve',
            name='departement_naissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département de naissance'),
        ),
    ]
