# Generated by Django 4.0 on 2022-01-25 12:03

from django.db import migrations, models

SPES = (
        ('ARTCIN', 'Cinéma', '1', 'art'),
        ('ARTTHEA', 'Théâtre', '1', 'art'),
        ('ARTMUS', 'Musique', '1', 'art'),
        ('ARTPLA', 'Arts plastiques', '1', 'art'),
        ('HISTGEO', 'Histoire-Géo-Pol', '1', None),
        ('MATH', 'Mathématiques', '1', None),
        ('HUMPHI', 'Humanités, littérature et philosophie', '2', None),
        ('PHYCHI', 'Physique-Chimie', '2', None),
        ('ECOSOC', 'Sciences économiques et sociales', '2', None),
        ('SVT', 'Sciences de la vie et de la terre', '3', None),
        ('LLCERANG', 'Anglais', '3', 'LLCE'),
        ('LLCERESP ', 'Espagnol', '3', 'LLCE'),
        ('ARTCIRQ', 'Arts du cirque', None, 'art'),
        ('ARTHIST', 'Histoire des arts', None, 'art'),
        ('ARTDAN', 'Danse', None, 'art'),
        ('BIOLO', 'Biologie - écologie', None, None),
        ('SCING', "Sciences de l'ingénieur", None, None),
        ('LLCERANGMC', 'Anglais monde contemporain', None, 'LLCE'),
        ('LLCERALL', 'Allemand', None, 'LLCE'),
        ('NUMINF', 'Numérique et sciences informatiques', None, None),
    )


def import_spe(apps, schema_editor):
    data = []
    Spe = apps.get_model("inscription", "Spe")
    for spe in SPES:
        code, intitule, groupe, te = spe
        data.append(Spe(code=code, intitule=intitule, groupe=groupe, type=te))
    db_alias = schema_editor.connection.alias
    Spe.objects.using(db_alias).bulk_create(data)


def delete_spe(apps, schema_editor):
    Spe = apps.get_model("inscription", "Spe")
    db_alias = schema_editor.connection.alias
    for spe in SPES:
        for code, intitule, groupe, type in spe:
            Spe.objects.using(db_alias).filter(code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_baseeleve_dys_baseeleve_ville_natale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, verbose_name='Code Spé')),
                ('intitule', models.CharField(max_length=9, verbose_name='Intitulé Spé')),
                ('groupe', models.CharField(max_length=100, verbose_name='Groupe Spé', blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type Spé')),
            ],
        ),
        migrations.AddField(
            model_name='baseeleve',
            name='spe1',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groupe': '1'}, related_name='spe1', to='inscription.Spe'),
        ),
        migrations.AddField(
            model_name='baseeleve',
            name='spe2',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groupe': '2'}, related_name='spe2', to='inscription.Spe'),
        ),
        migrations.AddField(
            model_name='baseeleve',
            name='spe3',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groupe': '3'}, related_name='spe3', to='inscription.Spe'),
        ),
        migrations.RunPython(import_spe,delete_spe),
    ]
