# Generated by Django 4.0 on 2022-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_departement_code_departement_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Commune'),
        ),
    ]
