# Generated by Django 4.0 on 2022-01-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_spe_baseeleve_spe1_baseeleve_spe2_baseeleve_spe3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseeleve',
            name='nom_usage',
            field=models.CharField(blank=True, help_text='Souhaites-tu être appelé par un nom différent de ton prénom ?', max_length=255, null=True, verbose_name="Nom d'usage"),
        ),
    ]
