# Generated by Django 4.0 on 2022-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_alter_baseeleve_nom_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeleve',
            name='niveau',
            field=models.CharField(choices=[('premiere', 'Première'), ('deter', 'Détermination (2nde)'), ('term', 'Terminale'), ('crepa', 'CREPA')], default='deter', max_length=10, verbose_name="Niveau d'inscription"),
        ),
    ]
