# Generated by Django 4.0 on 2022-01-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_alter_departement_nom_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='nom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='baseeleve',
            name='commune_naissance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.commune', verbose_name='Commune de naissance'),
        ),
        migrations.AlterField(
            model_name='baseeleve',
            name='departement_naissance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département de naissance'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.departement', verbose_name='Département'),
        ),
    ]
