# Generated by Django 4.0 on 2022-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_rename_nom_commune_name_rename_nom_departement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Code INSEE'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Code INSEE'),
        ),
    ]
