name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.13]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install gdal-bin libgdal-dev libpq-dev libmysqlclient-dev
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
    - name: Poetry install
      run: |
        poetry install
    - name: Try to make migrations
      run: |
        poetry run python manage.py migrate
