name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.9]
        poetry-version: [1.3.0]
        repo: ["lycee-experimental/docker-lxp"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install gdal-bin libgdal-dev libpq-dev libmysqlclient-dev
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Poetry install
      run: |
        poetry install
    - name: Try to make migrations
      run: |
        poetry run python manage.py migrate
    - name: Push to repo
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ matrix.repo }}
        event-type: update
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "django-lxp", "branch": "master"}'
    - name: Remote git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.NAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd block_volume/django-lxp/
          git pull
